#!/bin/sh
set -eu

cd /app

if [ "$1" = "start" ]; then
    echo "Starting Rust API server"
    exec /usr/local/bin/headless-rss serve --host 0.0.0.0 --port 8000
else
    echo "Executing command: $@"
    exec /usr/local/bin/headless-rss "$@"
fi
